# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- script: |
   curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
   python3 get-pip.py --user
   pip3 install pylint flake8 --user
  displayName: 'Install Python dependencies'

- script: |
   python3 -m pylint --version
   python3 -m pylint azureml --errors-only
  displayName: PyLint

- script: |
   flake8 --max-line-length=120
  displayName: Flake8